services:
  - type: web
    name: market-advisory-api
    runtime: docker
    repo: https://github.com/aqi-stuck/US-market-advisory-copilot
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: market-advisory-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_MODELS_BASE_URL
        value: https://models.inference.ai.azure.com
      - key: GITHUB_CHAT_MODEL_NAME
        value: gpt-4o-mini
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_VERSION
        value: 2024-02-01
      - key: API_KEY
        sync: false

  - type: cron
    name: weekly-market-ingestion
    runtime: docker
    repo: https://github.com/aqi-stuck/US-market-advisory-copilot
    plan: free
    schedule: "0 0 * * 0"
    dockerCommand: "python3 scripts/ingest.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: market-advisory-db
          property: connectionString
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: GITHUB_TOKEN
        sync: false

databases:
  - name: market-advisory-db
    databaseName: market_advisory
    user: market_user
    plan: free
    region: oregon